openapi: 3.0.0

info:
  title: Blog Management API
  description:
    This is API aims at allowing users to make blog posts and comment on them. 
    This acts as a mini social media app.
  contact:
    name: Nicole0509
    url: https://github.com/Nicole0509/spring-boot-blog-management
  version: 1.0.0

servers:
  - description: Local ENV
    url: http://localhost:8081
